services:
  api:
    build: .
    ports:
      - "3000:3000"
    container_name: mg_api
    image: mg_api:${IMAGE_TAG}
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432
      # REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      # - redis
    volumes:
      - .:/app
      - ./config/master.key:/rails/config/master.key:ro
    networks:
      - mg_network

  db:
    image: postgres
    container_name: mg_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mg_network

  # redis:
  #   image: redis
  #   ports:
  #     - "6379:6379"
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #

volumes:
  db_data:
    name: mg_db_data

networks:
  mg_network:
    name: mg_network
    driver: bridge
